#!/bin/bash

prog=mklivecd
excludeopts=""

usage () 
{
   echo "Usage: ${prog} [-x file/dir ...] [rootdir] outfile" >&2
   echo "  If omitted, rootdir is / (iso will exclude outfile)." >&2
   echo "  -x may be used multiple times to exclude files/directories," >&2
   echo "  which must include rootdir prefix." >&2
   exit 1
}

while getopts x: opt; do
   case "$opt" in
      x) excludeopts="${excludeopts} -x $OPTARG" ;;
      *) usage ;;
   esac
done
shift $(($OPTIND-1))
if [ $# != 2 ] && [ $# != 1 ]; then
   usage
fi
rootdir=""
if [ $# = 2 ]; then
   rootdir=$1
   if [ "${rootdir}" = "/" ]; then
      rootdir=""
   else
      if ! [ -d "${rootdir}" ]; then
         echo "${prog}: root directory \"${rootdir}\" is not a directory" >&2
         exit 1
      fi
   fi
   shift
fi
outfile=$1

if [ $(id -u) != 0 ]; then
   echo "${prog}: must run as root" >&2
   exit 1
fi
if ! [ -d "$(dirname $outfile)" ]; then
   echo "${prog}: problem with component of outfile path \"${outfile}\"" >&2
   exit 1
fi
if ! [ -f ${rootdir}/isolinux/isolinux.bin ]; then
   echo "${prog}: ${rootdir}/isolinux/isolinux.bin is missing" >&2
   exit 1
fi


mkdir -p ${rootdir}/isolinux
cp -f ${rootdir}/boot/vmlinuz      ${rootdir}/isolinux
cp -f ${rootdir}/boot/initrd       ${rootdir}/isolinux

echo "${prog}: Creating ${outfile} - this may take several minutes" >&2
mkisofs -x ${outfile} ${excludeopts} \
  -quiet -J -R -v -dir-mode 0755 -uid 0 -gid 0 -no-emul-boot -hide-rr-moved \
  -boot-load-size 4 -boot-info-table \
  -b isolinux/isolinux.bin -c isolinux/boot.cat ${rootdir:-/} \
  >${outfile} 2>${outfile}.log
if [ $? = 0 ]; then
   bytes=$(stat -c "%s" ${outfile})
   echo "${prog}: Created $(($bytes/1048576))MB ISO - see ${outfile}.log" >&2
   # clean up
   rm -f ${rootdir}/isolinux/vmlinuz
   rm -f ${rootdir}/isolinux/initrd
else
   echo "${prog}: Error creating ISO - see ${outfile}.log" >&2
   exit 1
fi
exit 0
