#!/bin/bash
############################################################################
# Copyright (C) 2007 Lawrence Livermore National Security, LLC
# Produced at Lawrence Livermore National Laboratory.
# Written by Jim Garlick <garlick@llnl.gov>.
# UCRL-CODE-235119
# 
# This file is part of nfsroot, a network root file system utility.
# 
# nfsroot is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# nfsroot is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with nfsroot; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
############################################################################
PATH=/sbin:/usr/sbin:/bin:/usr/bin
prog=nfsroot-kernel-pkg

kerneldir=/boot
modulesdir=/lib/modules
pxeconfig=${kerneldir}/pxelinux.cfg
pxebootmenu=${kerneldir}/pxelinux.msg

usage ()
{
   echo "Usage: ${prog} [-a <kver>|-d <kver>|-A|-D <kver>]" >&2
   echo " -a add kernel <kver>" >&2
   echo " -d del kernel <kver>" >&2
   echo " -A add all kernels present in ${modulesdir}" >&2
   echo " -D make <kver> the default" >&2
   exit 1
}

# List available kernel versions
#  Usage: list_kvers
list_kvers ()
{
   local kver

   for kver in $(find ${kerneldir} -name vmlinuz-\* | cut -d- -f2-); do
      if [ -f ${kerneldir}/vmlinuz-${kver} ]; then
         echo ${kver}
      fi
   done
}

# Regenerate list of boot options
#  Usage: regenerate_pxelinux_msg
regenerate_pxelinux_msg()
{
   local dflt=$(readlink ${kerneldir}/vmlinuz|cut -d- -f2-)
   echo "Boot options [default: ${dflt}]:" >${pxebootmenu}
   configpxe -f ${pxeconfig} -l           >>${pxebootmenu}
   return 0
}

# Update sym links for new kernel version
#  Usage: move_default_symlinks kver
move_default_symlinks ()
{
   echo "${prog}: default kernel is $1" >&2
   ln -sf vmlinuz-$1 ${kerneldir}/vmlinuz
   ln -sf vmlinux-$1 ${kerneldir}/vmlinux
   ln -sf System.map-$1 ${kerneldir}/System.map
   ln -sf initrd-$1 ${kerneldir}/initrd
   return 0
}

# Ensure that initrd and vmlinuz exist and point somewhere sane.
#  Usage: fixup_default_symlinks
fixup_default_symlinks ()
{
   if [ -h ${kerneldir}/initrd ] && [ -h ${kerneldir}/vmlinuz ]; then
      if [ -f ${kerneldir}/$(readlink ${kerneldir}/initrd) ]; then
         if [ -f ${kerneldir}/$(readlink ${kerneldir}/vmlinuz) ]; then
 	    return 0
         fi
      fi
   fi
   set $(list_kvers)
   if [ $# -gt 0 ]; then
      shift $(($#-1))
      move_default_symlinks $1
   else
      echo "${prog}: warning: could not select default kernel" >&2
   fi
   return 0
}

# Make symlinks so that kdump startup will load our nfsroot initrd.
#  Usage: add_kdump_links
add_kdump_links ()
{
   local kver

   for kver in $(list_kvers); do
      ln -sf initrd-${kver} ${kerneldir}/initrd-${kver}kdump.img
   done
}

# Ensure that all bootable files have read permission for other
fixup_permissions ()
{
   local kver

   for kver in $(list_kvers); do 
      chmod ugo+r ${kerneldir}/vmlinuz-${kver}
      chmod ugo+r ${kerneldir}/initrd-${kver}
   done
}

# silently exit if we were booted diskless
# FIXME: this may mess up configurations with non-shared rw root
grep -q BOOTIF /proc/cmdline 2>/dev/null && exit 0

while getopts a:d:AD: opt; do
   case "$opt" in
      a) fun=add; kver=$OPTARG ;;
      d) fun=del; kver=$OPTARG ;;
      A) fun=addall ;;
      D) fun=setdefault; kver=$OPTARG ;;
      *) usage ;;
   esac
done
shift $(($OPTIND-1))

# XXX Hack Alert!
# Snapshot chaos kernels have the date appended to the release name
# in the RPM, but not in the uname (vmlinux-* suffix/modules path).
# E.g. version-release  is 2.6.18-23patched.grondo.test.0802071445
# while uname is           2.6.18-23patched.grondo.test
# If kver is passed in with the suffix we chop it off here.
kver=$(echo -n ${kver} | sed -e 's/test\.[0-9]\{10\}/test/')

case "$fun" in
   add)
      mkinitrd_nfsroot -f ${kerneldir}/initrd-${kver} ${kver}
      cp -f ${pxeconfig} ${pxeconfig}~
      configpxe -f ${pxeconfig} -d ${kver} 2>/dev/null
      configpxe -f ${pxeconfig} -a ${kver}
      move_default_symlinks ${kver}  # last in wins!
      ;;
   del)
      rm -f ${kerneldir}/initrd-${kver}
      cp -f ${pxeconfig} ${pxeconfig}~
      configpxe -f ${pxeconfig} -d ${kver}
      ;;
   addall)
      cp -f ${pxeconfig} ${pxeconfig}~
      for kver in $(list_kvers); do 
         mkinitrd_nfsroot -f ${kerneldir}/initrd-${kver} ${kver}
         configpxe -f ${pxeconfig} -d ${kver} 2>/dev/null
         configpxe -f ${pxeconfig} -a ${kver}
      done
      ;;
   setdefault)
      for tmp in $(list_kvers); do
         if [ "${tmp}" = "$kver" ]; then
            move_default_symlinks ${kver} 
            break 
         fi
      done
      if [ "${tmp}" != "$kver" ]; then
         echo "${prog}: ${kver} is not a valid kernel" >&2
         exit 1
      fi
      ;;
   *)
      usage
      ;;
esac

fixup_default_symlinks
fixup_permissions
regenerate_pxelinux_msg
add_kdump_links

exit 0
