#!/bin/bash
# rebuild - called from nfsroot %post scriptlet to rebuild initramfs's

PATH=/sbin:/usr/sbin:/bin/:/usr/bin
prog=nfsroot-rebuild
kdir=/boot

if [ $# -ne 0 ]; then
    echo "Usage: $prog" >&2
    exit 1
fi

kver=
for file in $kdir/vmlinuz-*; do
    kver=$(basename $file|sed -e 's/vmlinuz-//')
    echo "${prog}: rebuilding $kver initramfs" >&2
    new-kernel-pkg --package kernel --mkinitrd --dracut --update $kver
    configpxe -a $kver 2>/dev/null
done
if [ -z "$kver" ]; then
    echo "${prog}: no kernels installed" >&2
    exit 0
fi
nfsroot-setdefault
