#!/bin/bash
# prerm - called from new-kernel-pkg with <kver> /boot/vmlinuz-<kver>

PATH=/sbin:/usr/sbin:/bin/:/usr/bin
prog=nfsroot-prerm

if [ $# -ne 2 ]; then
    echo "Usage: $prog kver vmlinuz-path" >&2
    exit 1
fi
kver=$1

configpxe -d $kver
nfsroot-setdefault -r $kver
