#!/bin/sh

echo "init=/etc/rc.nfsroot" >>$initdir/etc/cmdline
echo "root=dhcp" >>$initdir/etc/cmdline

# nfsroot issue 2
[ -f /etc/modprobe.conf ] && dracut_install /etc/modprobe.conf
dracut_install $(find /etc/modprobe.d/ -type f -name '*.conf')

# bz 1435
dracut_install awk
if test -d /etc/rdma; then
    mkdir -p ${initdir}/etc/rdma
    dracut_install $(find /etc/rdma/ -type f -name '*.conf')
    dracut_install $(find /etc/rdma/ -type f -name '*.awk')
fi

# nfsroot issue 12 - directory found missing by nbd module
mkdir -p $initdir/mount/

