#!/bin/bash
# postinst - called from new-kernel-pkg with <kver> /boot/vmlinuz-<kver>

PATH=/sbin:/usr/sbin:/bin/:/usr/bin
prog=nfsroot-postinst

if [ $# -ne 2 ]; then
    echo "Usage: $prog kver vmlinuz-path" >&2
    exit 1
fi
kver=$1

configpxe -a $kver
nfsroot-setdefault -d $kver 
